baseURL = "http://blog.greptilian.com/"
languageCode = "en-us"
title = "greptilian blog"
theme = "ananke"
[params]
  custom_css = ["css/custom.css"]
[permalinks]
  posts = "/:year/:month/:day/:slug/"
